import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { trpc } from "../utils/trpc";
import Hero from "../components/Hero";
import Footer from "../components/Footer";
import { formatFullName } from "../utils/helpers";
import Skills from "../components/Skills";

const Home: NextPage = () => {
    const { data: portfolio, isLoading, error } =
        trpc.portfolio.getPortfolio.useQuery(undefined, { refetchOnWindowFocus: false, refetchOnMount: false });

    if (isLoading)
        return <div>Loading</div>; // Add a spinner

    if (!portfolio || error)
        return <div>Error</div>;

    const title = `${formatFullName(portfolio.about.firstName, portfolio.about.lastName)}'s Portfolio`


    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />
                <Hero />
                <Skills />
                <Footer />
            </main>
        </>
    );
};

export default Home;
