import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { trpc } from "../utils/trpc";
import Hero from "../components/Hero";
import Footer from "../components/Footer";

const Home: NextPage = () => {
    const { data: portfolio, isLoading, error } = trpc.portfolio.getPortfolio.useQuery(undefined, { refetchOnWindowFocus: false });

    if (isLoading)
        return <div>Loading</div>; // Add a spinner

    if (!portfolio || error)
        return <div>Error</div>;


    return (
        <>
            <Head>
                <title>Mehdi Hyani&apos;s Portfolio</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar resume={portfolio.about.resume} />
                <Hero />
                <Footer />
            </main>
        </>
    );
};

export default Home;
