import React from "react";
import type { GetStaticProps, NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Navbar from "../components/Navbar";
// import { trpc } from "../utils/trpc";

export const getStaticProps: GetStaticProps = async () => {
    // const {} = trpc.
    return {
        props: {

        },
    }
}

const Home: NextPage = () => {
    const router = useRouter();

    React.useEffect(() => {
        console.log(router.query);
    }, [router.query]);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Navbar />

            </main>
        </>
    );
};

export default Home;
